# Generated by Django 4.2.1 on 2023-09-16 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_delete_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amount',
            new_name='syifa',
        ),
    ]
