# Generated by Django 4.2.1 on 2023-09-16 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_amount_product_syifa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='syifa',
            new_name='amount',
        ),
    ]
